version: '3.8'
services:
  user:
    hostname: user
    build:
      context: ./context/user
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_user
    environment:
      - DATABASE_HOST=postgres_user

  postgres_user:
    image: postgres:15.3
    hostname: postgres_user
    container_name: postgres_user
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./context/user/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "pg_isready"
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 29092:29092
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_CLUSTER_ID: microworld
      KAFKA_BROKER_ID: 1
      KAFKA_ENABLE_KRAFT: 'no'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      KAFKA_CFG_LISTENERS: 'PLAINTEXT: //:9092'
      KAFKA_PORT: 9092
      KAFKA_LISTENERS:
        INTERNAL://:9092,
        EXTERNAL://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS:
        INTERNAL://kafka:9092,
        EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  zookeeper:
    hostname: zookeper
    container_name: zookeper
    image: zookeeper:latest
    ports:
      - 2181

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9080:8080
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=microworld
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeper:2181
      - KAFKA_CLUSTERS_0_READONLY=false