version: '3.8'
services:
  user:
    hostname: user
    build:
      context: ./context/user
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_user
    environment:
      - DATABASE_HOST=localhost

  postgres_user:
    image: postgres:15.3
    hostname: postgres_user
    container_name: postgres_user
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - 55432:5432
    volumes:
      - ./context/user/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "pg_isready"
      interval: 10s
      timeout: 5s
      retries: 5