spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:55432/users
    hikari:
      username: user
      password: password
      maximum-pool-size: 2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${FORMAT_SQL:false}
    hibernate:
      ddl-auto: create
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
