spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:55432/users
    hikari:
      username: user
      password: password
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
