name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: |
          cd microworld/context/user
          ./gradlew build --console=plain

      - name: Run tests
        run: |
          cd microworld/context/user
          ./gradlew test --console=plain